export const data = {
  workExperience: [
    {
      logo: "https://sandconsole.com/icons/wood-mark-logo.jpg",
      location: "Kathmandu Nepal (remote)",
      company: "Sand Console",
      url: "https://sandconsole.com",
      title: "Frontend Developer (Next.js)",
      from: "July 2024",
      to: "Present",
    },
    {
      logo: "https://metalogic.com.np/metalogo.png",
      location: "Lalitpur, Nepal",
      company: "Metalogic Software",
      url: "https://metalogic.com.np",
      title: "Full Stack Developer (Node & React)",
      from: "Feb 2024",
      to: "Jul 2024",
    },
    {
      logo: "https://avatars.githubusercontent.com/u/140021323?s=100&v=10",
      location: "California USA (remote)",
      company: "StartupHire",
      title: "Frontend Developer",
      url: "https://www.linkedin.com/company/startuphire/about",
      from: "Jan 2024",
      to: "Feb 2024",
    },
    {
      logo: "https://avatars.githubusercontent.com/u/140021323?s=100&v=10",
      location: "California USA (remote)",
      company: "StartupHire",
      title: "Frontend Developer Intern",
      url: "https://www.linkedin.com/company/startuphire/about",
      from: "Sep 2023",
      to: "Dec 2023",
    },
  ],
  skills: {
    languages: ["JavaScript", "TypeScript", "Golang"],
    frontend: [
      "HTML",
      "CSS",
      "React",
      "Next.js",
      "Framer Motion",
      "Tailwind CSS",
      "React Query",
      "Redux Toolkit",
      "React Hook Form",
      "Zod",
      "Turborepo",
      "Radix UI",
      "ShadCN UI",
    ],
    backend: ["Node.js", "Golang", "REST APIs", "JWT Authenctication"],
    databases: ["MongoDB", "PostgreSQL", "MySQL", "Sqlite"],
    Tools: ["Linux", "GitHub", "Github Actions", "Docker"],
  },
};
