export const data = {
  workExperience: [
    {
      logo: "https://sandconsole.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsandconsole-logo-blue.5c89443a.svg&w=384&q=75",
      location: "Kathmandu Nepal (remote)",
      company: "Frontend Developer",
      url: "https://sandconsole.com",
      title: "Frontend Developer (Next.js)",
      from: "July 2024",
      to: "Present",
    },
    {
      logo: "https://metalogic.com.np/metalogo.png",
      location: "Lalitpur, Nepal",
      company: "Metalogic Software",
      url: "https://metalogic.com.np",
      title: "Full Stack Developer (Node & React)",
      from: "Feb 2023",
      to: "Jul 2023",
    },
    {
      logo: "https://media.licdn.com/dms/image/C4D0BAQFVBaWozNJXfg/company-logo_200_200/0/1630545258536/startuphire_logo?e=1724889600&v=beta&t=pZQwoZRmyFNjiiLZzDe74ykDU2uFOI3X5lCvd0slf7Y",
      location: "California USA (remote)",
      company: "StartupHire",
      title: "Frontend Developer",
      url: "https://www.linkedin.com/company/startuphire/about",
      from: "Jan 2023",
      to: "Feb 2023",
    },
    {
      logo: "https://media.licdn.com/dms/image/C4D0BAQFVBaWozNJXfg/company-logo_200_200/0/1630545258536/startuphire_logo?e=1724889600&v=beta&t=pZQwoZRmyFNjiiLZzDe74ykDU2uFOI3X5lCvd0slf7Y",
      location: "California USA (remote)",
      company: "StartupHire",
      title: "Frontend Developer Intern",
      url: "https://www.linkedin.com/company/startuphire/about",
      from: "Sep 2023",
      to: "Dec 2023",
    },
  ],
  skills: {
    languages: ["JavaScript", "TypeScript", "Golang"],
    frontend: [
      "HTML",
      "CSS",
      "React",
      "Next.js",
      "Framer Motion",
      "Tailwind CSS",
      "React Query",
      "Redux Toolkit",
      "React Hook Form",
      "Zod",
      "Turborepo",
      "Radix UI",
      "ShadCN UI",
    ],
    backend: ["Node.js", "Golang", "REST APIs", "JWT Authenctication"],
    databases: ["MongoDB", "PostgreSQL", "MySQL", "Sqlite"],
    Tools: ["Linux", "GitHub", "Github Actions", "Docker"],
  },
};
