export const data = {
  workExperience: [
    // {
    //   logo: "https://media.licdn.com/dms/image/v2/C4E0BAQGbHpMSZeKkEw/company-logo_200_200/company-logo_200_200/0/1630573974203/frosticsatellite_logo?e=1753315200&v=beta&t=3r4oOzdCCmmqtLK8RFwU96amX4YDTLiS4YRIXhvI7Iw",
    //   location: "USA (Remote)",
    //   company: "Forstic Satellite",
    //   url: "https://snipverse.com",
    //   title: "Frontend Developer (Next.js)",
    //   from: "November 2024",
    //   to: "Present",
    // },
    {
      logo: "https://media.licdn.com/dms/image/v2/D560BAQErNJFYuuW7tQ/company-logo_200_200/company-logo_200_200/0/1690836777977/sandconsole_logo?e=1753315200&v=beta&t=r4cSYj-a-8CZRmd89fdkavpbAQyoIPDn7T-Rdn_Riq8",
      location: "Kathmandu Nepal (remote)",
      company: "Sand Console",
      url: "https://sandconsole.com",
      title: "Frontend Developer (Next.js)",
      from: "July 2024",
      to: "December 2024",
    },
    {
      logo: "https://media.licdn.com/dms/image/v2/C4D0BAQFVBaWozNJXfg/company-logo_200_200/company-logo_200_200/0/1630545258536/startuphire_logo?e=1753315200&v=beta&t=6-6KC1f63vojkrCbc-lVwSnY-jI6JQEgjqiJBmObrHs",
      location: "California USA (remote)",
      company: "StartupHire",
      title: "Frontend Developer",
      url: "https://www.linkedin.com/company/startuphire/about",
      from: "Sep 2023",
      to: "May 2024",
    },
  ],
  skills: {
    languages: ["JavaScript", "TypeScript", "Golang"],
    frontend: [
      "HTML",
      "CSS",
      "React",
      "Next.js",
      "Framer Motion",
      "Tailwind CSS",
      "React Query",
      "Redux Toolkit",
      "React Hook Form",
      "Zod",
      "Turborepo",
      "Radix UI",
      "ShadCN UI",
    ],
    backend: ["Node.js", "Golang", "REST APIs", "JWT Authenctication"],
    databases: ["MongoDB", "PostgreSQL", "MySQL", "Sqlite"],
    Tools: ["Linux", "GitHub", "Github Actions", "Docker"],
  },
};
